#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.


#  Source utility functions.
source "$OPENSHIFT_REPO_DIR/.openshift/lib/utils"


#  On slave/serving gears, need to do the install as part of deploy
#  so check if its needed. Just ensure the custom Node[.js] version is
#  installed.
ensure_node_is_installed

# Set custom node version
setup_path_for_custom_node_version

# Run bower
npm install bower -g
$OPENSHIFT_REPO_DIR/node_modules/.bin/bower install

# Run semantic gulp
cd $OPENSHIFT_REPO_DIR/semantic
gulp build

# Run gulp
cd $OPENSHIFT_REPO_DIR
gulp build --env production



